// Copyright (c) 2014, tvelliott
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions are met:
//
// * Redistributions of source code must retain the above copyright notice, this
//   list of conditions and the following disclaimer.
//
// * Redistributions in binary form must reproduce the above copyright notice,
//   this list of conditions and the following disclaimer in the documentation
//   and/or other materials provided with the distribution.
//
// * Neither the name of the {organization} nor the names of its
//   contributors may be used to endorse or promote products derived from
//   this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
// AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
// IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
// DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
// FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
// DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
// SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
// CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
// OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
// OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

package jPCBSim;

import java.util.prefs.Preferences;
import javax.swing.*;
import java.io.*;

public class fileLocationDiaglog extends javax.swing.JFrame
{

  private Preferences prefs;
//Create a file chooser
  final JFileChooser fc = new JFileChooser();

  static public final String JPCBSIM_OPENEMS_BIN = "jpcbsim.openems.bin";
  static public final String JPCBSIM_HYP2MAT_BIN = "jpcbsim.hyp2mat.bin";
  static public final String JPCBSIM_NF2FF_BIN = "jpcbsim.nf2ff.bin";
  static public final String JPCBSIM_PROJECT_DIR = "jpcbsim.project.dir";
  static public final String JPCBSIM_PARAVIEW_BIN = "jpcbsim.paraview.bin";

  private String openems_path;
  private String hyp2mat_path;
  private String nf2ff_path;
  private String project_path;
  private String paraview_path;

  public fileLocationDiaglog()
  {
    initComponents();
    prefs = Preferences.userRoot().node(this.getClass().getName());
    //fc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
    fc.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);
    readPaths();
  }


  public String getPath( String path )
  {
    return prefs.get(path,"");
  }

  public void readPaths()
  {
    try {
      openems_path = prefs.get(JPCBSIM_OPENEMS_BIN,"");
      hyp2mat_path = prefs.get(JPCBSIM_HYP2MAT_BIN,"");
      nf2ff_path = prefs.get(JPCBSIM_NF2FF_BIN,"");
      project_path = prefs.get(JPCBSIM_PROJECT_DIR,"");
      paraview_path = prefs.get(JPCBSIM_PARAVIEW_BIN,"");
      if(openems_path!=null) openems_tf.setText(openems_path);
      if(hyp2mat_path!=null) hyp2mat_tf.setText(hyp2mat_path);
      if(nf2ff_path!=null) nf2ff_tf.setText(nf2ff_path);
      if(project_path!=null) projects_tf.setText(project_path);
      if(paraview_path!=null) paraview_tf.setText(paraview_path);
    } catch(Exception e) {
      e.printStackTrace();
    }
  }

  public void writePaths()
  {
    try {
      prefs.put(JPCBSIM_OPENEMS_BIN, openems_tf.getText());
      prefs.put(JPCBSIM_HYP2MAT_BIN, hyp2mat_tf.getText());
      prefs.put(JPCBSIM_NF2FF_BIN, nf2ff_tf.getText());
      prefs.put(JPCBSIM_PROJECT_DIR, projects_tf.getText());
      prefs.put(JPCBSIM_PARAVIEW_BIN, paraview_tf.getText());
    } catch(Exception e) {
      e.printStackTrace();
    }
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents()
  {

    jLabel1 = new javax.swing.JLabel();
    jLabel2 = new javax.swing.JLabel();
    jLabel3 = new javax.swing.JLabel();
    jLabel4 = new javax.swing.JLabel();
    cancel = new javax.swing.JButton();
    finished = new javax.swing.JButton();
    openems_tf = new javax.swing.JTextField();
    hyp2mat_tf = new javax.swing.JTextField();
    nf2ff_tf = new javax.swing.JTextField();
    findopenems = new javax.swing.JButton();
    findhyp2mat = new javax.swing.JButton();
    findnf2ff = new javax.swing.JButton();
    jLabel5 = new javax.swing.JLabel();
    projects_tf = new javax.swing.JTextField();
    findproject = new javax.swing.JButton();
    findparaview = new javax.swing.JButton();
    jLabel6 = new javax.swing.JLabel();
    paraview_tf = new javax.swing.JTextField();

    setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
    setTitle("File Locations");

    jLabel1.setText("Please Select The File Locations For The Following Executable Files From The OpenEMS Project And Others");

    jLabel2.setText("OpenEMS FDTD Engine (openEMS):");

    jLabel3.setText("Hyp2Mat (hyp2mat):");

    jLabel4.setText("Paraview");

    cancel.setText("Cancel");
    cancel.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        cancelActionPerformed(evt);
      }
    });

    finished.setText("Finished");
    finished.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        finishedActionPerformed(evt);
      }
    });

    openems_tf.setColumns(48);

    hyp2mat_tf.setColumns(48);

    nf2ff_tf.setColumns(48);

    findopenems.setText("...");
    findopenems.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        findopenemsActionPerformed(evt);
      }
    });

    findhyp2mat.setText("...");
    findhyp2mat.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        findhyp2matActionPerformed(evt);
      }
    });

    findnf2ff.setText("...");
    findnf2ff.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        findnf2ffActionPerformed(evt);
      }
    });

    jLabel5.setText("Please Select The jPCBSim Simultation Project Folder");

    projects_tf.setColumns(48);

    findproject.setText("...");
    findproject.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        findprojectActionPerformed(evt);
      }
    });

    findparaview.setText("...");
    findparaview.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        findparaviewActionPerformed(evt);
      }
    });

    jLabel6.setText("NF2FF:");

    paraview_tf.setColumns(48);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cancel)
                .addGap(149, 149, 149)
                .addComponent(finished)
                .addGap(140, 140, 140))
      .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                          .addGroup(layout.createSequentialGroup()
                                    .addGap(21, 21, 21)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel2)
                                                .addComponent(jLabel3)
                                                .addComponent(jLabel6))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(openems_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(findopenems))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(hyp2mat_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(findhyp2mat))
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                    .addComponent(nf2ff_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(findnf2ff)
                                                    .addGap(8, 8, 8))))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(jLabel5)
                                            .addGap(55, 55, 55))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(projects_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addComponent(findproject))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jLabel4)
                                                    .addGap(190, 190, 190)
                                                    .addComponent(paraview_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 529, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(findparaview)))
                                            .addGap(11, 11, 11))))
                          .addGroup(layout.createSequentialGroup()
                                    .addGap(100, 100, 100)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 793, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(77, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                          .addComponent(jLabel2)
                          .addComponent(openems_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                          .addComponent(findopenems))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                          .addComponent(jLabel3)
                          .addComponent(findhyp2mat)
                          .addComponent(hyp2mat_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                          .addComponent(findnf2ff)
                          .addComponent(nf2ff_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                          .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                          .addComponent(paraview_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                          .addComponent(findparaview)
                          .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                          .addComponent(projects_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                          .addComponent(findproject))
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                          .addComponent(cancel)
                          .addComponent(finished))
                .addGap(18, 18, 18))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void finishedActionPerformed(java.awt.event.ActionEvent evt)  //GEN-FIRST:event_finishedActionPerformed
  {
    writePaths();
    dispose();
  }//GEN-LAST:event_finishedActionPerformed

  private void cancelActionPerformed(java.awt.event.ActionEvent evt)  //GEN-FIRST:event_cancelActionPerformed
  {
    dispose();
  }//GEN-LAST:event_cancelActionPerformed

  private void findopenemsActionPerformed(java.awt.event.ActionEvent evt)  //GEN-FIRST:event_findopenemsActionPerformed
  {
    //In response to a button click:
    int returnVal = fc.showOpenDialog(this);
    if (returnVal == JFileChooser.APPROVE_OPTION) {
      File file = fc.getSelectedFile();
      openems_tf.setText(file.toString());
    }
  }//GEN-LAST:event_findopenemsActionPerformed

  private void findhyp2matActionPerformed(java.awt.event.ActionEvent evt)  //GEN-FIRST:event_findhyp2matActionPerformed
  {
    //In response to a button click:
    int returnVal = fc.showOpenDialog(this);
    if (returnVal == JFileChooser.APPROVE_OPTION) {
      File file = fc.getSelectedFile();
      hyp2mat_tf.setText(file.toString());
    }
  }//GEN-LAST:event_findhyp2matActionPerformed

  private void findnf2ffActionPerformed(java.awt.event.ActionEvent evt)  //GEN-FIRST:event_findnf2ffActionPerformed
  {
    //In response to a button click:
    int returnVal = fc.showOpenDialog(this);
    if (returnVal == JFileChooser.APPROVE_OPTION) {
      File file = fc.getSelectedFile();
      nf2ff_tf.setText(file.toString());
    }
  }//GEN-LAST:event_findnf2ffActionPerformed

  private void findprojectActionPerformed(java.awt.event.ActionEvent evt)  //GEN-FIRST:event_findprojectActionPerformed
  {
    //In response to a button click:
    int returnVal = fc.showOpenDialog(this);
    if (returnVal == JFileChooser.APPROVE_OPTION) {
      File file = fc.getSelectedFile();
      projects_tf.setText(file.toString());
    }
  }//GEN-LAST:event_findprojectActionPerformed

  private void findparaviewActionPerformed(java.awt.event.ActionEvent evt)  //GEN-FIRST:event_findparaviewActionPerformed
  {
    // TODO add your handling code here:
    //In response to a button click:
    int returnVal = fc.showOpenDialog(this);
    if (returnVal == JFileChooser.APPROVE_OPTION) {
      File file = fc.getSelectedFile();
      paraview_tf.setText(file.toString());
    }
  }//GEN-LAST:event_findparaviewActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[])
  {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
     * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(fileLocationDiaglog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(fileLocationDiaglog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(fileLocationDiaglog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(fileLocationDiaglog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new fileLocationDiaglog().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton cancel;
  private javax.swing.JButton findhyp2mat;
  private javax.swing.JButton findnf2ff;
  private javax.swing.JButton findopenems;
  private javax.swing.JButton findparaview;
  private javax.swing.JButton findproject;
  private javax.swing.JButton finished;
  private javax.swing.JTextField hyp2mat_tf;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JLabel jLabel6;
  private javax.swing.JTextField nf2ff_tf;
  private javax.swing.JTextField openems_tf;
  private javax.swing.JTextField paraview_tf;
  private javax.swing.JTextField projects_tf;
  // End of variables declaration//GEN-END:variables
}
