//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2014.04.22 at 07:23:13 AM PDT
//


package jPCBSim;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="R" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="G" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="B" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="a" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "FillColor")
public class FillColor
{

  @XmlAttribute(name = "R")
  protected String r;
  @XmlAttribute(name = "G")
  protected String g;
  @XmlAttribute(name = "B")
  protected String b;
  @XmlAttribute(name = "a")
  protected String a;

  /**
   * Gets the value of the r property.
   *
   * @return
   *     possible object is
   *     {@link String }
   *
   */
  public String getR()
  {
    return r;
  }

  /**
   * Sets the value of the r property.
   *
   * @param value
   *     allowed object is
   *     {@link String }
   *
   */
  public void setR(String value)
  {
    this.r = value;
  }

  /**
   * Gets the value of the g property.
   *
   * @return
   *     possible object is
   *     {@link String }
   *
   */
  public String getG()
  {
    return g;
  }

  /**
   * Sets the value of the g property.
   *
   * @param value
   *     allowed object is
   *     {@link String }
   *
   */
  public void setG(String value)
  {
    this.g = value;
  }

  /**
   * Gets the value of the b property.
   *
   * @return
   *     possible object is
   *     {@link String }
   *
   */
  public String getB()
  {
    return b;
  }

  /**
   * Sets the value of the b property.
   *
   * @param value
   *     allowed object is
   *     {@link String }
   *
   */
  public void setB(String value)
  {
    this.b = value;
  }

  /**
   * Gets the value of the a property.
   *
   * @return
   *     possible object is
   *     {@link String }
   *
   */
  public String getA()
  {
    return a;
  }

  /**
   * Sets the value of the a property.
   *
   * @param value
   *     allowed object is
   *     {@link String }
   *
   */
  public void setA(String value)
  {
    this.a = value;
  }

}
