// Copyright (c) 2014, tvelliott
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions are met:
//
// * Redistributions of source code must retain the above copyright notice, this
//   list of conditions and the following disclaimer.
//
// * Redistributions in binary form must reproduce the above copyright notice,
//   this list of conditions and the following disclaimer in the documentation
//   and/or other materials provided with the distribution.
//
// * Neither the name of the {organization} nor the names of its
//   contributors may be used to endorse or promote products derived from
//   this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
// AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
// IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
// DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
// FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
// DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
// SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
// CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
// OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
// OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

package jPCBSim;

public class microStrip extends javax.swing.JFrame
{
  calcs mcalcs;

  public microStrip()
  {
    initComponents();
    mcalcs = new calcs(this);
    equiv_comp_unit.setText("NA");
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents()
  {

    jPanel1 = new javax.swing.JPanel();
    jPanel4 = new javax.swing.JPanel();
    jPanel6 = new javax.swing.JPanel();
    jLabel2 = new javax.swing.JLabel();
    er_combo = new javax.swing.JComboBox();
    Er_tf = new javax.swing.JTextField();
    jPanel26 = new javax.swing.JPanel();
    jLabel3 = new javax.swing.JLabel();
    pcb_height_combo = new javax.swing.JComboBox();
    pcb_height_tf = new javax.swing.JTextField();
    units_label1 = new javax.swing.JLabel();
    jPanel27 = new javax.swing.JPanel();
    jLabel4 = new javax.swing.JLabel();
    W_tf = new javax.swing.JTextField();
    unit_label2 = new javax.swing.JLabel();
    jPanel28 = new javax.swing.JPanel();
    jLabel5 = new javax.swing.JLabel();
    L_tf = new javax.swing.JTextField();
    unit_label3 = new javax.swing.JLabel();
    end_effect_len = new javax.swing.JLabel();
    jPanel29 = new javax.swing.JPanel();
    jLabel7 = new javax.swing.JLabel();
    equiv_comp_val_tf = new javax.swing.JTextField();
    equiv_comp_unit = new javax.swing.JLabel();
    end_effect_comp = new javax.swing.JLabel();
    jPanel5 = new javax.swing.JPanel();
    jPanel33 = new javax.swing.JPanel();
    jLabel10 = new javax.swing.JLabel();
    freq_combo = new javax.swing.JComboBox();
    freq_ghz_tf = new javax.swing.JTextField();
    jPanel34 = new javax.swing.JPanel();
    jLabel11 = new javax.swing.JLabel();
    Zo_combo = new javax.swing.JComboBox();
    Zo_tf = new javax.swing.JTextField();
    jLabel18 = new javax.swing.JLabel();
    jPanel35 = new javax.swing.JPanel();
    jLabel12 = new javax.swing.JLabel();
    angle_tf = new javax.swing.JTextField();
    jLabel20 = new javax.swing.JLabel();
    jPanel36 = new javax.swing.JPanel();
    XcXl = new javax.swing.JLabel();
    Xlc_tf = new javax.swing.JTextField();
    jLabel6 = new javax.swing.JLabel();
    jPanel30 = new javax.swing.JPanel();
    warnings = new javax.swing.JLabel();
    jPanel2 = new javax.swing.JPanel();
    jLabel1 = new javax.swing.JLabel();
    jPanel3 = new javax.swing.JPanel();
    use_comp_val = new javax.swing.JButton();
    use_angle = new javax.swing.JButton();
    use_length = new javax.swing.JButton();
    jLabel19 = new javax.swing.JLabel();
    units_combo = new javax.swing.JComboBox();

    setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);

    jPanel1.setLayout(new java.awt.GridLayout(1, 2));

    jPanel4.setLayout(new java.awt.GridLayout(5, 1));

    jPanel6.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

    jLabel2.setText("Er PCB/Substrate");
    jPanel6.add(jLabel2);

    er_combo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "FR4 = 4.2", "ROG4003C = 3.38", "ROG4350B = 3.48", "ALUMINA = 9.5" }));
    er_combo.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        er_comboActionPerformed(evt);
      }
    });
    jPanel6.add(er_combo);

    Er_tf.setColumns(4);
    Er_tf.setText("4.2");
    Er_tf.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        Er_tfActionPerformed(evt);
      }
    });
    jPanel6.add(Er_tf);

    jPanel4.add(jPanel6);

    jPanel26.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

    jLabel3.setText("(H)eight PCB/Substrate");
    jPanel26.add(jLabel3);

    pcb_height_combo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "16", "31", "62" }));
    pcb_height_combo.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        pcb_height_comboActionPerformed(evt);
      }
    });
    jPanel26.add(pcb_height_combo);

    pcb_height_tf.setColumns(3);
    pcb_height_tf.setText("16");
    jPanel26.add(pcb_height_tf);

    units_label1.setText("mils");
    jPanel26.add(units_label1);

    jPanel4.add(jPanel26);

    jPanel27.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

    jLabel4.setText("(W)idth");
    jPanel27.add(jLabel4);

    W_tf.setColumns(8);
    W_tf.setText("36.8933");
    jPanel27.add(W_tf);

    unit_label2.setText("mils");
    jPanel27.add(unit_label2);

    jPanel4.add(jPanel27);

    jPanel28.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

    jLabel5.setText("(L)ength");
    jPanel28.add(jLabel5);

    L_tf.setColumns(8);
    L_tf.setText("69.7057");
    jPanel28.add(L_tf);

    unit_label3.setText("mils");
    jPanel28.add(unit_label3);
    jPanel28.add(end_effect_len);

    jPanel4.add(jPanel28);

    jPanel29.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

    jLabel7.setText("Equiv Comp");
    jPanel29.add(jLabel7);

    equiv_comp_val_tf.setColumns(8);
    equiv_comp_val_tf.setText("0.0");
    equiv_comp_val_tf.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        equiv_comp_val_tfActionPerformed(evt);
      }
    });
    jPanel29.add(equiv_comp_val_tf);

    equiv_comp_unit.setText("pF");
    jPanel29.add(equiv_comp_unit);
    jPanel29.add(end_effect_comp);

    jPanel4.add(jPanel29);

    jPanel1.add(jPanel4);

    jPanel5.setLayout(new java.awt.GridLayout(5, 1));

    jPanel33.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

    jLabel10.setText("Frequency GHz");
    jPanel33.add(jLabel10);

    freq_combo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0.160", "0.460", "0.915", "2.4", "4.97", "5.8" }));
    freq_combo.setSelectedIndex(4);
    freq_combo.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        freq_comboActionPerformed(evt);
      }
    });
    jPanel33.add(freq_combo);

    freq_ghz_tf.setColumns(5);
    freq_ghz_tf.setText("4.97");
    jPanel33.add(freq_ghz_tf);

    jPanel5.add(jPanel33);

    jPanel34.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

    jLabel11.setText("Zo");
    jPanel34.add(jLabel11);

    Zo_combo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Transmission Line 50", "Capactive Shunt 30", "Inductive Shunt 100", "Inductive Series 100" }));
    Zo_combo.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        Zo_comboActionPerformed(evt);
      }
    });
    jPanel34.add(Zo_combo);

    Zo_tf.setColumns(4);
    Zo_tf.setText("50");
    jPanel34.add(Zo_tf);

    jLabel18.setText("Ohm");
    jPanel34.add(jLabel18);

    jPanel5.add(jPanel34);

    jPanel35.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

    jLabel12.setText("Angle");
    jPanel35.add(jLabel12);

    angle_tf.setColumns(5);
    angle_tf.setText("90.0");
    jPanel35.add(angle_tf);

    jLabel20.setText("Degrees");
    jPanel35.add(jLabel20);

    jPanel5.add(jPanel35);

    jPanel36.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

    XcXl.setText("Xc/Xl ");
    jPanel36.add(XcXl);

    Xlc_tf.setColumns(5);
    Xlc_tf.setText("0.0");
    jPanel36.add(Xlc_tf);

    jLabel6.setText("Ohm");
    jPanel36.add(jLabel6);

    jPanel5.add(jPanel36);

    jPanel30.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

    warnings.setText("Warnings:");
    jPanel30.add(warnings);

    jPanel5.add(jPanel30);

    jPanel1.add(jPanel5);

    getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

    jLabel1.setText("Microstrip Calculator");
    jPanel2.add(jLabel1);

    getContentPane().add(jPanel2, java.awt.BorderLayout.NORTH);

    use_comp_val.setText("Comp->Len");
    use_comp_val.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        use_comp_valActionPerformed(evt);
      }
    });
    jPanel3.add(use_comp_val);

    use_angle.setText("Ang->Comp");
    use_angle.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        use_angleActionPerformed(evt);
      }
    });
    jPanel3.add(use_angle);

    use_length.setText("Len->Comp");
    use_length.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        use_lengthActionPerformed(evt);
      }
    });
    jPanel3.add(use_length);

    jLabel19.setText("Units");
    jPanel3.add(jLabel19);

    units_combo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "mils", "mm", "inch", " " }));
    units_combo.setEnabled(false);
    jPanel3.add(units_combo);

    getContentPane().add(jPanel3, java.awt.BorderLayout.SOUTH);

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void use_comp_valActionPerformed(java.awt.event.ActionEvent evt)  //GEN-FIRST:event_use_comp_valActionPerformed
  {
    end_effect_len.setText("");
    end_effect_comp.setText("");
    mcalcs.use_comp(
      new Double(Er_tf.getText()),
      new Double(pcb_height_tf.getText()),
      new Double(freq_ghz_tf.getText()),
      new Double(Zo_tf.getText()),
      new Double(equiv_comp_val_tf.getText()) );
    W_tf.setText( String.format("%3.1f", mcalcs.W) );
    L_tf.setText( String.format("%3.1f", mcalcs.length) );
    angle_tf.setText( String.format("%3.1f", mcalcs.angle) );
    Xlc_tf.setText( String.format("%3.1f", mcalcs.Xlc) );
    warnings.setText( mcalcs.warnings );

    if( Zo_combo.getSelectedIndex() == 1) {
      end_effect_len.setText( String.format(" len x 0.95: %3.1f",mcalcs.length*0.95));
    }

  }//GEN-LAST:event_use_comp_valActionPerformed

  private void use_angleActionPerformed(java.awt.event.ActionEvent evt)  //GEN-FIRST:event_use_angleActionPerformed
  {
    end_effect_len.setText("");
    end_effect_comp.setText("");

    mcalcs.use_angle(
      new Double(Er_tf.getText()),
      new Double(pcb_height_tf.getText()),
      new Double(freq_ghz_tf.getText()),
      new Double(Zo_tf.getText()),
      new Double(angle_tf.getText()) );
    W_tf.setText( String.format("%3.1f", mcalcs.W) );
    L_tf.setText( String.format("%3.1f", mcalcs.length) );
    equiv_comp_val_tf.setText( String.format("%3.2f", mcalcs.comp_val) );
    Xlc_tf.setText( String.format("%3.1f", mcalcs.Xlc) );
    warnings.setText( mcalcs.warnings );
    if( Zo_combo.getSelectedIndex() == 1) {
      end_effect_comp.setText( String.format(" comp x 1.05: %3.1f",mcalcs.comp_val*1.05));
    }
  }//GEN-LAST:event_use_angleActionPerformed
  private void use_lengthActionPerformed(java.awt.event.ActionEvent evt)  //GEN-FIRST:event_use_lengthActionPerformed
  {
    end_effect_len.setText("");
    end_effect_comp.setText("");
    mcalcs.use_length(
      new Double(Er_tf.getText()),
      new Double(pcb_height_tf.getText()),
      new Double(freq_ghz_tf.getText()),
      new Double(Zo_tf.getText()),
      new Double(L_tf.getText()) );
    W_tf.setText( String.format("%3.1f", mcalcs.W) );
    angle_tf.setText( String.format("%3.1f", mcalcs.angle) );
    equiv_comp_val_tf.setText( String.format("%3.2f", mcalcs.comp_val) );
    Xlc_tf.setText( String.format("%3.1f", mcalcs.Xlc) );
    warnings.setText( mcalcs.warnings );
    if( Zo_combo.getSelectedIndex() == 1) {
      end_effect_comp.setText( String.format(" comp x 1.05: %3.1f",mcalcs.comp_val*1.05));
    }
  }//GEN-LAST:event_use_lengthActionPerformed

  private void Er_tfActionPerformed(java.awt.event.ActionEvent evt)  //GEN-FIRST:event_Er_tfActionPerformed
  {
    // TODO add your handling code here:
  }//GEN-LAST:event_Er_tfActionPerformed
  private void equiv_comp_val_tfActionPerformed(java.awt.event.ActionEvent evt)  //GEN-FIRST:event_equiv_comp_val_tfActionPerformed
  {
    // TODO add your handling code here:
  }//GEN-LAST:event_equiv_comp_val_tfActionPerformed

  private void er_comboActionPerformed(java.awt.event.ActionEvent evt)  //GEN-FIRST:event_er_comboActionPerformed
  {
    if( er_combo.getSelectedIndex() == 0) Er_tf.setText("4.2");
    else if( er_combo.getSelectedIndex() == 1) Er_tf.setText("3.38");
    else if( er_combo.getSelectedIndex() == 2) Er_tf.setText("3.48");
    else if( er_combo.getSelectedIndex() == 3) Er_tf.setText("9.5");
  }//GEN-LAST:event_er_comboActionPerformed
  private void pcb_height_comboActionPerformed(java.awt.event.ActionEvent evt)  //GEN-FIRST:event_pcb_height_comboActionPerformed
  {
    if( pcb_height_combo.getSelectedIndex() == 0) pcb_height_tf.setText("16");
    else if( pcb_height_combo.getSelectedIndex() == 1) pcb_height_tf.setText("31");
    else if( pcb_height_combo.getSelectedIndex() == 2) pcb_height_tf.setText("62");
  }//GEN-LAST:event_pcb_height_comboActionPerformed
  private void freq_comboActionPerformed(java.awt.event.ActionEvent evt)  //GEN-FIRST:event_freq_comboActionPerformed
  {
    if( freq_combo.getSelectedIndex() == 0) freq_ghz_tf.setText("0.160");
    else if( freq_combo.getSelectedIndex() == 1) freq_ghz_tf.setText("0.460");
    else if( freq_combo.getSelectedIndex() == 2) freq_ghz_tf.setText("0.915");
    else if( freq_combo.getSelectedIndex() == 3) freq_ghz_tf.setText("2.4");
    else if( freq_combo.getSelectedIndex() == 4) freq_ghz_tf.setText("4.97");
    else if( freq_combo.getSelectedIndex() == 5) freq_ghz_tf.setText("5.8");
  }//GEN-LAST:event_freq_comboActionPerformed
  private void Zo_comboActionPerformed(java.awt.event.ActionEvent evt)  //GEN-FIRST:event_Zo_comboActionPerformed
  {
    if( Zo_combo.getSelectedIndex() == 0) {
      Zo_tf.setText("50");
      equiv_comp_unit.setText("NA");
    } else if( Zo_combo.getSelectedIndex() == 1) {
      Zo_tf.setText("30");
      equiv_comp_unit.setText("pF");
    } else if( Zo_combo.getSelectedIndex() == 2) {
      Zo_tf.setText("100");
      equiv_comp_unit.setText("nH");
    } else if( Zo_combo.getSelectedIndex() == 3) {
      Zo_tf.setText("100");
      equiv_comp_unit.setText("nH");
    }
  }//GEN-LAST:event_Zo_comboActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[])
  {
    /*
     * Set the Nimbus look and feel
     */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /*
     * If Nimbus (introduced in Java SE 6) is not available, stay with the
     * default look and feel. For details see
     * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(microStrip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(microStrip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(microStrip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(microStrip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /*
     * Create and display the form
     */
    java.awt.EventQueue.invokeLater(new Runnable() {

      public void run() {
        new microStrip().setVisible(true);
      }
    });
  }
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JTextField Er_tf;
  private javax.swing.JTextField L_tf;
  private javax.swing.JTextField W_tf;
  private javax.swing.JLabel XcXl;
  private javax.swing.JTextField Xlc_tf;
  private javax.swing.JComboBox Zo_combo;
  private javax.swing.JTextField Zo_tf;
  private javax.swing.JTextField angle_tf;
  private javax.swing.JLabel end_effect_comp;
  private javax.swing.JLabel end_effect_len;
  private javax.swing.JLabel equiv_comp_unit;
  private javax.swing.JTextField equiv_comp_val_tf;
  private javax.swing.JComboBox er_combo;
  private javax.swing.JComboBox freq_combo;
  private javax.swing.JTextField freq_ghz_tf;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel10;
  private javax.swing.JLabel jLabel11;
  private javax.swing.JLabel jLabel12;
  private javax.swing.JLabel jLabel18;
  private javax.swing.JLabel jLabel19;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel20;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JLabel jLabel6;
  private javax.swing.JLabel jLabel7;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel jPanel2;
  private javax.swing.JPanel jPanel26;
  private javax.swing.JPanel jPanel27;
  private javax.swing.JPanel jPanel28;
  private javax.swing.JPanel jPanel29;
  private javax.swing.JPanel jPanel3;
  private javax.swing.JPanel jPanel30;
  private javax.swing.JPanel jPanel33;
  private javax.swing.JPanel jPanel34;
  private javax.swing.JPanel jPanel35;
  private javax.swing.JPanel jPanel36;
  private javax.swing.JPanel jPanel4;
  private javax.swing.JPanel jPanel5;
  private javax.swing.JPanel jPanel6;
  private javax.swing.JComboBox pcb_height_combo;
  private javax.swing.JTextField pcb_height_tf;
  private javax.swing.JLabel unit_label2;
  private javax.swing.JLabel unit_label3;
  private javax.swing.JComboBox units_combo;
  private javax.swing.JLabel units_label1;
  private javax.swing.JButton use_angle;
  private javax.swing.JButton use_comp_val;
  private javax.swing.JButton use_length;
  private javax.swing.JLabel warnings;
  // End of variables declaration//GEN-END:variables
}
