//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2014.04.22 at 07:23:13 AM PDT
//


package jPCBSim;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each
 * Java content interface and Java element interface
 * generated in the jPCBSim package.
 * <p>An ObjectFactory allows you to programatically
 * construct new instances of the Java representation
 * for XML content. The Java representation of XML
 * content can consist of schema derived interfaces
 * and classes representing the binding of schema
 * type definitions, element declarations and model
 * groups.  Factory methods for each of these are
 * provided in this class.
 *
 */
@XmlRegistry
public class ObjectFactory
{


  /**
   * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: jPCBSim
   *
   */
  public ObjectFactory()
  {
  }

  /**
   * Create an instance of {@link Primitives }
   *
   */
  public Primitives createPrimitives()
  {
    return new Primitives();
  }

  /**
   * Create an instance of {@link OpenEMS }
   *
   */
  public OpenEMS createOpenEMS()
  {
    return new OpenEMS();
  }

  /**
   * Create an instance of {@link OpenEMS.ContinuousStructure }
   *
   */
  public OpenEMS.ContinuousStructure createOpenEMSContinuousStructure()
  {
    return new OpenEMS.ContinuousStructure();
  }

  /**
   * Create an instance of {@link OpenEMS.ContinuousStructure.Properties }
   *
   */
  public OpenEMS.ContinuousStructure.Properties createOpenEMSContinuousStructureProperties()
  {
    return new OpenEMS.ContinuousStructure.Properties();
  }

  /**
   * Create an instance of {@link OpenEMS.ContinuousStructure.Properties.LorentzMaterial }
   *
   */
  public OpenEMS.ContinuousStructure.Properties.LorentzMaterial createOpenEMSContinuousStructurePropertiesLorentzMaterial()
  {
    return new OpenEMS.ContinuousStructure.Properties.LorentzMaterial();
  }

  /**
   * Create an instance of {@link OpenEMS.ContinuousStructure.Properties.Material }
   *
   */
  public OpenEMS.ContinuousStructure.Properties.Material createOpenEMSContinuousStructurePropertiesMaterial()
  {
    return new OpenEMS.ContinuousStructure.Properties.Material();
  }

  /**
   * Create an instance of {@link OpenEMS.ContinuousStructure.RectilinearGrid }
   *
   */
  public OpenEMS.ContinuousStructure.RectilinearGrid createOpenEMSContinuousStructureRectilinearGrid()
  {
    return new OpenEMS.ContinuousStructure.RectilinearGrid();
  }

  /**
   * Create an instance of {@link OpenEMS.FDTD }
   *
   */
  public OpenEMS.FDTD createOpenEMSFDTD()
  {
    return new OpenEMS.FDTD();
  }

  /**
   * Create an instance of {@link Primitives.Cylinder }
   *
   */
  public Primitives.Cylinder createPrimitivesCylinder()
  {
    return new Primitives.Cylinder();
  }

  /**
   * Create an instance of {@link Primitives.LinPoly }
   *
   */
  public Primitives.LinPoly createPrimitivesLinPoly()
  {
    return new Primitives.LinPoly();
  }

  /**
   * Create an instance of {@link Primitives.Polygon }
   *
   */
  public Primitives.Polygon createPrimitivesPolygon()
  {
    return new Primitives.Polygon();
  }

  /**
   * Create an instance of {@link Primitives.Box }
   *
   */
  public Primitives.Box createPrimitivesBox()
  {
    return new Primitives.Box();
  }

  /**
   * Create an instance of {@link Excitation }
   *
   */
  public Excitation createExcitation()
  {
    return new Excitation();
  }

  /**
   * Create an instance of {@link FillColor }
   *
   */
  public FillColor createFillColor()
  {
    return new FillColor();
  }

  /**
   * Create an instance of {@link EdgeColor }
   *
   */
  public EdgeColor createEdgeColor()
  {
    return new EdgeColor();
  }

  /**
   * Create an instance of {@link Weight }
   *
   */
  public Weight createWeight()
  {
    return new Weight();
  }

  /**
   * Create an instance of {@link OpenEMS.ContinuousStructure.Properties.Metal }
   *
   */
  public OpenEMS.ContinuousStructure.Properties.Metal createOpenEMSContinuousStructurePropertiesMetal()
  {
    return new OpenEMS.ContinuousStructure.Properties.Metal();
  }

  /**
   * Create an instance of {@link OpenEMS.ContinuousStructure.Properties.LumpedElement }
   *
   */
  public OpenEMS.ContinuousStructure.Properties.LumpedElement createOpenEMSContinuousStructurePropertiesLumpedElement()
  {
    return new OpenEMS.ContinuousStructure.Properties.LumpedElement();
  }

  /**
   * Create an instance of {@link OpenEMS.ContinuousStructure.Properties.ProbeBox }
   *
   */
  public OpenEMS.ContinuousStructure.Properties.ProbeBox createOpenEMSContinuousStructurePropertiesProbeBox()
  {
    return new OpenEMS.ContinuousStructure.Properties.ProbeBox();
  }

  /**
   * Create an instance of {@link OpenEMS.ContinuousStructure.Properties.DumpBox }
   *
   */
  public OpenEMS.ContinuousStructure.Properties.DumpBox createOpenEMSContinuousStructurePropertiesDumpBox()
  {
    return new OpenEMS.ContinuousStructure.Properties.DumpBox();
  }

  /**
   * Create an instance of {@link OpenEMS.ContinuousStructure.Properties.LorentzMaterial.Property }
   *
   */
  public OpenEMS.ContinuousStructure.Properties.LorentzMaterial.Property createOpenEMSContinuousStructurePropertiesLorentzMaterialProperty()
  {
    return new OpenEMS.ContinuousStructure.Properties.LorentzMaterial.Property();
  }

  /**
   * Create an instance of {@link OpenEMS.ContinuousStructure.Properties.Material.Property }
   *
   */
  public OpenEMS.ContinuousStructure.Properties.Material.Property createOpenEMSContinuousStructurePropertiesMaterialProperty()
  {
    return new OpenEMS.ContinuousStructure.Properties.Material.Property();
  }

  /**
   * Create an instance of {@link OpenEMS.ContinuousStructure.RectilinearGrid.XLines }
   *
   */
  public OpenEMS.ContinuousStructure.RectilinearGrid.XLines createOpenEMSContinuousStructureRectilinearGridXLines()
  {
    return new OpenEMS.ContinuousStructure.RectilinearGrid.XLines();
  }

  /**
   * Create an instance of {@link OpenEMS.ContinuousStructure.RectilinearGrid.YLines }
   *
   */
  public OpenEMS.ContinuousStructure.RectilinearGrid.YLines createOpenEMSContinuousStructureRectilinearGridYLines()
  {
    return new OpenEMS.ContinuousStructure.RectilinearGrid.YLines();
  }

  /**
   * Create an instance of {@link OpenEMS.ContinuousStructure.RectilinearGrid.ZLines }
   *
   */
  public OpenEMS.ContinuousStructure.RectilinearGrid.ZLines createOpenEMSContinuousStructureRectilinearGridZLines()
  {
    return new OpenEMS.ContinuousStructure.RectilinearGrid.ZLines();
  }

  /**
   * Create an instance of {@link OpenEMS.FDTD.BoundaryCond }
   *
   */
  public OpenEMS.FDTD.BoundaryCond createOpenEMSFDTDBoundaryCond()
  {
    return new OpenEMS.FDTD.BoundaryCond();
  }

  /**
   * Create an instance of {@link Primitives.Cylinder.P1 }
   *
   */
  public Primitives.Cylinder.P1 createPrimitivesCylinderP1()
  {
    return new Primitives.Cylinder.P1();
  }

  /**
   * Create an instance of {@link Primitives.Cylinder.P2 }
   *
   */
  public Primitives.Cylinder.P2 createPrimitivesCylinderP2()
  {
    return new Primitives.Cylinder.P2();
  }

  /**
   * Create an instance of {@link Primitives.LinPoly.Vertex }
   *
   */
  public Primitives.LinPoly.Vertex createPrimitivesLinPolyVertex()
  {
    return new Primitives.LinPoly.Vertex();
  }

  /**
   * Create an instance of {@link Primitives.Polygon.Vertex }
   *
   */
  public Primitives.Polygon.Vertex createPrimitivesPolygonVertex()
  {
    return new Primitives.Polygon.Vertex();
  }

  /**
   * Create an instance of {@link Primitives.Box.P1 }
   *
   */
  public Primitives.Box.P1 createPrimitivesBoxP1()
  {
    return new Primitives.Box.P1();
  }

  /**
   * Create an instance of {@link Primitives.Box.P2 }
   *
   */
  public Primitives.Box.P2 createPrimitivesBoxP2()
  {
    return new Primitives.Box.P2();
  }

}
