//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.09.14 at 10:55:23 AM PDT 
//


package jPCBSim;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Box" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="P1" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute name="X" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="Y" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="Z" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="P2" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute name="X" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="Y" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="Z" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="Priority" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Polygon" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Vertex" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute name="X1" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="X2" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="Priority" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="Elevation" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="NormDir" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="QtyVertices" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="LinPoly" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Vertex" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute name="X1" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="X2" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="Priority" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="Elevation" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="NormDir" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="QtyVertices" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="Length" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Cylinder" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="P1" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute name="X" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="Y" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="Z" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="P2" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute name="X" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="Y" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="Z" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="Priority" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="Radius" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "box",
    "polygon",
    "linPoly",
    "cylinder"
})
@XmlRootElement(name = "Primitives")
public class Primitives {

    @XmlElement(name = "Box")
    protected List<Primitives.Box> box;
    @XmlElement(name = "Polygon")
    protected List<Primitives.Polygon> polygon;
    @XmlElement(name = "LinPoly")
    protected List<Primitives.LinPoly> linPoly;
    @XmlElement(name = "Cylinder")
    protected List<Primitives.Cylinder> cylinder;

    /**
     * Gets the value of the box property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the box property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBox().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Primitives.Box }
     * 
     * 
     */
    public List<Primitives.Box> getBox() {
        if (box == null) {
            box = new ArrayList<Primitives.Box>();
        }
        return this.box;
    }

    /**
     * Gets the value of the polygon property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the polygon property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPolygon().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Primitives.Polygon }
     * 
     * 
     */
    public List<Primitives.Polygon> getPolygon() {
        if (polygon == null) {
            polygon = new ArrayList<Primitives.Polygon>();
        }
        return this.polygon;
    }

    /**
     * Gets the value of the linPoly property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the linPoly property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLinPoly().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Primitives.LinPoly }
     * 
     * 
     */
    public List<Primitives.LinPoly> getLinPoly() {
        if (linPoly == null) {
            linPoly = new ArrayList<Primitives.LinPoly>();
        }
        return this.linPoly;
    }

    /**
     * Gets the value of the cylinder property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the cylinder property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCylinder().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Primitives.Cylinder }
     * 
     * 
     */
    public List<Primitives.Cylinder> getCylinder() {
        if (cylinder == null) {
            cylinder = new ArrayList<Primitives.Cylinder>();
        }
        return this.cylinder;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="P1" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attribute name="X" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="Y" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="Z" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="P2" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attribute name="X" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="Y" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="Z" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *       &lt;attribute name="Priority" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "p1",
        "p2"
    })
    public static class Box {

        @XmlElement(name = "P1")
        protected List<Primitives.Box.P1> p1;
        @XmlElement(name = "P2")
        protected List<Primitives.Box.P2> p2;
        @XmlAttribute(name = "Priority")
        protected String priority;

        /**
         * Gets the value of the p1 property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the p1 property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getP1().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Primitives.Box.P1 }
         * 
         * 
         */
        public List<Primitives.Box.P1> getP1() {
            if (p1 == null) {
                p1 = new ArrayList<Primitives.Box.P1>();
            }
            return this.p1;
        }

        /**
         * Gets the value of the p2 property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the p2 property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getP2().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Primitives.Box.P2 }
         * 
         * 
         */
        public List<Primitives.Box.P2> getP2() {
            if (p2 == null) {
                p2 = new ArrayList<Primitives.Box.P2>();
            }
            return this.p2;
        }

        /**
         * Gets the value of the priority property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPriority() {
            return priority;
        }

        /**
         * Sets the value of the priority property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPriority(String value) {
            this.priority = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute name="X" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="Y" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="Z" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class P1 {

            @XmlAttribute(name = "X")
            protected String x;
            @XmlAttribute(name = "Y")
            protected String y;
            @XmlAttribute(name = "Z")
            protected String z;

            /**
             * Gets the value of the x property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getX() {
                return x;
            }

            /**
             * Sets the value of the x property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setX(String value) {
                this.x = value;
            }

            /**
             * Gets the value of the y property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getY() {
                return y;
            }

            /**
             * Sets the value of the y property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setY(String value) {
                this.y = value;
            }

            /**
             * Gets the value of the z property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getZ() {
                return z;
            }

            /**
             * Sets the value of the z property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setZ(String value) {
                this.z = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute name="X" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="Y" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="Z" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class P2 {

            @XmlAttribute(name = "X")
            protected String x;
            @XmlAttribute(name = "Y")
            protected String y;
            @XmlAttribute(name = "Z")
            protected String z;

            /**
             * Gets the value of the x property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getX() {
                return x;
            }

            /**
             * Sets the value of the x property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setX(String value) {
                this.x = value;
            }

            /**
             * Gets the value of the y property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getY() {
                return y;
            }

            /**
             * Sets the value of the y property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setY(String value) {
                this.y = value;
            }

            /**
             * Gets the value of the z property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getZ() {
                return z;
            }

            /**
             * Sets the value of the z property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setZ(String value) {
                this.z = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="P1" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attribute name="X" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="Y" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="Z" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="P2" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attribute name="X" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="Y" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="Z" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *       &lt;attribute name="Priority" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="Radius" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "p1",
        "p2"
    })
    public static class Cylinder {

        @XmlElement(name = "P1")
        protected List<Primitives.Cylinder.P1> p1;
        @XmlElement(name = "P2")
        protected List<Primitives.Cylinder.P2> p2;
        @XmlAttribute(name = "Priority")
        protected String priority;
        @XmlAttribute(name = "Radius")
        protected String radius;

        /**
         * Gets the value of the p1 property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the p1 property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getP1().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Primitives.Cylinder.P1 }
         * 
         * 
         */
        public List<Primitives.Cylinder.P1> getP1() {
            if (p1 == null) {
                p1 = new ArrayList<Primitives.Cylinder.P1>();
            }
            return this.p1;
        }

        /**
         * Gets the value of the p2 property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the p2 property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getP2().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Primitives.Cylinder.P2 }
         * 
         * 
         */
        public List<Primitives.Cylinder.P2> getP2() {
            if (p2 == null) {
                p2 = new ArrayList<Primitives.Cylinder.P2>();
            }
            return this.p2;
        }

        /**
         * Gets the value of the priority property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPriority() {
            return priority;
        }

        /**
         * Sets the value of the priority property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPriority(String value) {
            this.priority = value;
        }

        /**
         * Gets the value of the radius property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRadius() {
            return radius;
        }

        /**
         * Sets the value of the radius property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRadius(String value) {
            this.radius = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute name="X" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="Y" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="Z" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class P1 {

            @XmlAttribute(name = "X")
            protected String x;
            @XmlAttribute(name = "Y")
            protected String y;
            @XmlAttribute(name = "Z")
            protected String z;

            /**
             * Gets the value of the x property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getX() {
                return x;
            }

            /**
             * Sets the value of the x property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setX(String value) {
                this.x = value;
            }

            /**
             * Gets the value of the y property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getY() {
                return y;
            }

            /**
             * Sets the value of the y property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setY(String value) {
                this.y = value;
            }

            /**
             * Gets the value of the z property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getZ() {
                return z;
            }

            /**
             * Sets the value of the z property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setZ(String value) {
                this.z = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute name="X" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="Y" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="Z" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class P2 {

            @XmlAttribute(name = "X")
            protected String x;
            @XmlAttribute(name = "Y")
            protected String y;
            @XmlAttribute(name = "Z")
            protected String z;

            /**
             * Gets the value of the x property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getX() {
                return x;
            }

            /**
             * Sets the value of the x property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setX(String value) {
                this.x = value;
            }

            /**
             * Gets the value of the y property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getY() {
                return y;
            }

            /**
             * Sets the value of the y property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setY(String value) {
                this.y = value;
            }

            /**
             * Gets the value of the z property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getZ() {
                return z;
            }

            /**
             * Sets the value of the z property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setZ(String value) {
                this.z = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Vertex" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attribute name="X1" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="X2" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *       &lt;attribute name="Priority" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="Elevation" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="NormDir" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="QtyVertices" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="Length" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "vertex"
    })
    public static class LinPoly {

        @XmlElement(name = "Vertex")
        protected List<Primitives.LinPoly.Vertex> vertex;
        @XmlAttribute(name = "Priority")
        protected String priority;
        @XmlAttribute(name = "Elevation")
        protected String elevation;
        @XmlAttribute(name = "NormDir")
        protected String normDir;
        @XmlAttribute(name = "QtyVertices")
        protected String qtyVertices;
        @XmlAttribute(name = "Length")
        protected String length;

        /**
         * Gets the value of the vertex property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the vertex property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getVertex().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Primitives.LinPoly.Vertex }
         * 
         * 
         */
        public List<Primitives.LinPoly.Vertex> getVertex() {
            if (vertex == null) {
                vertex = new ArrayList<Primitives.LinPoly.Vertex>();
            }
            return this.vertex;
        }

        /**
         * Gets the value of the priority property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPriority() {
            return priority;
        }

        /**
         * Sets the value of the priority property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPriority(String value) {
            this.priority = value;
        }

        /**
         * Gets the value of the elevation property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getElevation() {
            return elevation;
        }

        /**
         * Sets the value of the elevation property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setElevation(String value) {
            this.elevation = value;
        }

        /**
         * Gets the value of the normDir property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNormDir() {
            return normDir;
        }

        /**
         * Sets the value of the normDir property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNormDir(String value) {
            this.normDir = value;
        }

        /**
         * Gets the value of the qtyVertices property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getQtyVertices() {
            return qtyVertices;
        }

        /**
         * Sets the value of the qtyVertices property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setQtyVertices(String value) {
            this.qtyVertices = value;
        }

        /**
         * Gets the value of the length property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLength() {
            return length;
        }

        /**
         * Sets the value of the length property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLength(String value) {
            this.length = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute name="X1" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="X2" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class Vertex {

            @XmlAttribute(name = "X1")
            protected String x1;
            @XmlAttribute(name = "X2")
            protected String x2;

            /**
             * Gets the value of the x1 property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getX1() {
                return x1;
            }

            /**
             * Sets the value of the x1 property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setX1(String value) {
                this.x1 = value;
            }

            /**
             * Gets the value of the x2 property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getX2() {
                return x2;
            }

            /**
             * Sets the value of the x2 property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setX2(String value) {
                this.x2 = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Vertex" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attribute name="X1" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="X2" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *       &lt;attribute name="Priority" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="Elevation" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="NormDir" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="QtyVertices" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "vertex"
    })
    public static class Polygon {

        @XmlElement(name = "Vertex")
        protected List<Primitives.Polygon.Vertex> vertex;
        @XmlAttribute(name = "Priority")
        protected String priority;
        @XmlAttribute(name = "Elevation")
        protected String elevation;
        @XmlAttribute(name = "NormDir")
        protected String normDir;
        @XmlAttribute(name = "QtyVertices")
        protected String qtyVertices;

        /**
         * Gets the value of the vertex property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the vertex property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getVertex().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Primitives.Polygon.Vertex }
         * 
         * 
         */
        public List<Primitives.Polygon.Vertex> getVertex() {
            if (vertex == null) {
                vertex = new ArrayList<Primitives.Polygon.Vertex>();
            }
            return this.vertex;
        }

        /**
         * Gets the value of the priority property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPriority() {
            return priority;
        }

        /**
         * Sets the value of the priority property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPriority(String value) {
            this.priority = value;
        }

        /**
         * Gets the value of the elevation property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getElevation() {
            return elevation;
        }

        /**
         * Sets the value of the elevation property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setElevation(String value) {
            this.elevation = value;
        }

        /**
         * Gets the value of the normDir property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNormDir() {
            return normDir;
        }

        /**
         * Sets the value of the normDir property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNormDir(String value) {
            this.normDir = value;
        }

        /**
         * Gets the value of the qtyVertices property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getQtyVertices() {
            return qtyVertices;
        }

        /**
         * Sets the value of the qtyVertices property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setQtyVertices(String value) {
            this.qtyVertices = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute name="X1" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="X2" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class Vertex {

            @XmlAttribute(name = "X1")
            protected String x1;
            @XmlAttribute(name = "X2")
            protected String x2;

            /**
             * Gets the value of the x1 property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getX1() {
                return x1;
            }

            /**
             * Sets the value of the x1 property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setX1(String value) {
                this.x1 = value;
            }

            /**
             * Gets the value of the x2 property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getX2() {
                return x2;
            }

            /**
             * Sets the value of the x2 property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setX2(String value) {
                this.x2 = value;
            }

        }

    }

}
